# 这是一个nginx配置文件的示例

# 代理ForgeOrder服务
upstream forgeorder {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
    server 127.0.0.1:8083;
    server 127.0.0.1:8084;
}

server {
    listen 5000;
    server_name ForgeOrder;

    # 代理前端服务，用于开发时Vite
    location / {
        proxy_pass http://127.0.0.1:5173;
    };

    # 代理前端服务，用于生产环境
    # location / {
    #     root /path/to/ForgeOrder/frontend/dist; # 替换为真实地址
    #     try_files $uri $uri/ /index.html;
    # }

    location /api/ {
        proxy_pass http://forgeorder;
    }

}